#!/usr/bin/env python3
"""Reproducibly generate modern Chakra Python protobuf bindings on demand."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from typing import Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_RELATIVE_PATH = Path(
    "simul/astra-sim/extern/graph_frontend/chakra/schema/protobuf/et_def.proto"
)
GENERATED_RELATIVE_DIR = Path("generated/chakra_pb2")
BINDING_NAME = "et_def_pb2.py"
STAMP_NAME = ".et_def_pb2_bootstrap.json"


class ChakraVenvUnavailable(RuntimeError):
    """Raised only when the dedicated Chakra virtual environment is absent."""


def chakra_venv_fix_commands() -> str:
    return (
        "venv_py12/bin/python -m venv venv_chakra ; "
        'venv_chakra/bin/pip install "protobuf==5.29.*" '
        '"grpcio-tools==1.68.1"'
    )


def _chakra_python(repository_root: Path) -> Path:
    candidates: list[Path] = []
    configured = os.environ.get("CHAKRA_VENV_PYTHON")
    if configured:
        candidates.append(Path(configured))
    candidates.extend(
        [
            repository_root / "venv_chakra/bin/python",
            Path(sys.prefix).parent / "venv_chakra/bin/python",
        ]
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    checked = ", ".join(str(candidate) for candidate in candidates)
    raise ChakraVenvUnavailable(
        "venv_chakra is absent; fix with exactly: "
        f"{chakra_venv_fix_commands()} (checked: {checked})"
    )


def _command_output(command: list[str], description: str) -> str:
    try:
        completed = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as error:
        detail = (error.stderr or error.stdout or "").strip()
        raise RuntimeError(f"failed to query {description}: {detail}") from error
    return completed.stdout.strip()


def _tool_versions(chakra_python: Path) -> tuple[str, str]:
    protoc = _command_output(
        [str(chakra_python), "-m", "grpc_tools.protoc", "--version"],
        "grpc_tools.protoc version",
    )
    runtime = _command_output(
        [
            str(chakra_python),
            "-c",
            "import google.protobuf; print(google.protobuf.__version__)",
        ],
        "protobuf runtime version",
    )
    return protoc, runtime


def _schema_hash(schema: Path) -> str:
    digest = hashlib.sha256()
    with schema.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _read_stamp(stamp_path: Path) -> dict[str, object] | None:
    try:
        parsed = json.loads(stamp_path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return None
    return parsed if isinstance(parsed, dict) else None


def _is_current(
    binding: Path,
    stamp_path: Path,
    schema: Path,
    schema_hash: str,
    protoc_version: str,
) -> bool:
    if not binding.is_file():
        return False
    stamp = _read_stamp(stamp_path)
    if stamp is not None:
        return (
            stamp.get("schema_sha256") == schema_hash
            and stamp.get("protoc_version") == protoc_version
        )

    # Adopt a binding generated manually with the documented command.  Future
    # bootstrap generations carry the content hash stamp above.
    try:
        header = binding.read_text(encoding="utf-8", errors="replace")[:512]
        return (
            "# source: et_def.proto" in header
            and "# Generated by the protocol buffer compiler." in header
            and binding.stat().st_mtime_ns >= schema.stat().st_mtime_ns
        )
    except OSError:
        return False


def _write_stamp(path: Path, contents: dict[str, object]) -> None:
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            prefix=f".{path.name}.",
            suffix=".tmp",
            dir=path.parent,
            delete=False,
        ) as stream:
            temporary_name = stream.name
            json.dump(contents, stream, indent=2, sort_keys=True)
            stream.write("\n")
        os.replace(temporary_name, path)
        temporary_name = None
    finally:
        if temporary_name is not None:
            try:
                Path(temporary_name).unlink()
            except FileNotFoundError:
                pass


def bootstrap_bindings(
    *, repository_root: Path = REPOSITORY_ROOT, force: bool = False
) -> Path:
    """Ensure ``generated/chakra_pb2/et_def_pb2.py`` is current.

    Returns the generated module directory.  Generation is atomic, and an
    already-current output is never rewritten.
    """

    repository_root = Path(repository_root).resolve()
    schema = repository_root / SCHEMA_RELATIVE_PATH
    output_dir = repository_root / GENERATED_RELATIVE_DIR
    binding = output_dir / BINDING_NAME
    stamp_path = output_dir / STAMP_NAME
    chakra_python = _chakra_python(repository_root)
    if not schema.is_file():
        raise FileNotFoundError(
            f"missing authoritative Chakra schema {schema}; initialize it with: "
            "git submodule update --init --recursive simul/astra-sim"
        )

    protoc_version, runtime_version = _tool_versions(chakra_python)
    print(
        "Chakra protobuf bootstrap: "
        f"protoc={protoc_version}; runtime={runtime_version}; "
        f"python={chakra_python}"
    )
    schema_hash = _schema_hash(schema)
    if not force and _is_current(
        binding, stamp_path, schema, schema_hash, protoc_version
    ):
        print(f"Chakra protobuf bootstrap: current, no-op: {binding}")
        return output_dir

    output_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix=".chakra_pb2_build.", dir=output_dir
    ) as temporary:
        temporary_dir = Path(temporary)
        command = [
            str(chakra_python),
            "-m",
            "grpc_tools.protoc",
            f"-I{schema.parent}",
            f"--python_out={temporary_dir}",
            str(schema),
        ]
        try:
            subprocess.run(command, check=True, capture_output=True, text=True)
        except subprocess.CalledProcessError as error:
            detail = (error.stderr or error.stdout or "").strip()
            raise RuntimeError(f"Chakra protobuf generation failed: {detail}") from error
        generated = temporary_dir / BINDING_NAME
        if not generated.is_file():
            raise RuntimeError(f"protoc did not produce expected binding: {generated}")
        os.replace(generated, binding)

    _write_stamp(
        stamp_path,
        {
            "binding": BINDING_NAME,
            "protobuf_runtime_version": runtime_version,
            "protoc_version": protoc_version,
            "schema": str(SCHEMA_RELATIVE_PATH),
            "schema_sha256": schema_hash,
        },
    )
    print(f"Chakra protobuf bootstrap: generated: {binding}")
    return output_dir


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force", action="store_true", help="regenerate even when the output is current"
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = _build_parser().parse_args(argv)
    try:
        bootstrap_bindings(force=arguments.force)
    except (ChakraVenvUnavailable, FileNotFoundError, RuntimeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
